apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isva-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: PATCHED_BY_KUSTOMIZE
  resources:
    requests:
      storage: 2Gi
